# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: paulopkl
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: chatbot
# "service" is the name of this project. This will also be added to your AWS resource names.
service: chatbot

provider:
  name: aws
  runtime: nodejs20.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - polly:SynthesizeSpeech
      Resource: "*"
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource:
        - arn:aws:s3:::chatbot-test-paulo/* # Replace with your actual bucket name

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: "*"

# Replace with your actual bucket name
# resources:
#   Resources:
#     TextToSpeechBucket:
#       Type: AWS::S3::Bucket
#       Properties:
#         BucketName: chatbot-test-paulo
#         AccessControl: PublicRead
